# Generated by Django 4.2.6 on 2023-10-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_descripcion_task_description_task_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
