# Generated by Django 4.2.6 on 2023-10-25 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='data',
        ),
        migrations.AddField(
            model_name='task',
            name='Registro_Actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='Registro_Creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
