# Generated by Django 4.2.6 on 2023-10-31 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_data_task_registro_actualizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='campo1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='campo2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='campo3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='foto',
            field=models.FileField(null=True, upload_to='productos'),
        ),
    ]
